
name: Sphinx to GitHub Pages

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: doc/source
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages